output_root: output

data_ingestion:
  root_dir: output/data_ingestion
  processed_data_path: data/processed_cancer.csv 
  train_data_path: output/data_ingestion/train.csv
  test_data_path: output/data_ingestion/test.csv
  raw_data_path: output/data_ingestion/data.csv

data_transformation:
  root_dir: output/data_transformation
  train_data_path: output/data_ingestion/train.csv
  test_data_path: output/data_ingestion/test.csv
  train_array_path: output/data_transformation/train_array.npy
  test_array_path: output/data_transformation/test_array.npy
  preprocessor_obj_file_path: output/data_transformation/preprocessor.pkl

model_trainer:
  root_dir: output/model_trainer
  train_array_path: output/data_transformation/train_array.npy
  test_array_path: output/data_transformation/test_array.npy
  trained_model_file_path: output/model_trainer/model.pkl